/* user-dictionary.c generated by valac 0.20.1.19-a6516, the Vala compiler
 * generated from user-dictionary.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <libkkc-test.h>
#include <libkkc/libkkc-internals.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gstdio.h>
#include <stdio.h>
#include <locale.h>


#define TYPE_USER_SEGMENT_DICTIONARY_TESTS (user_segment_dictionary_tests_get_type ())
#define USER_SEGMENT_DICTIONARY_TESTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_SEGMENT_DICTIONARY_TESTS, UserSegmentDictionaryTests))
#define USER_SEGMENT_DICTIONARY_TESTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_USER_SEGMENT_DICTIONARY_TESTS, UserSegmentDictionaryTestsClass))
#define IS_USER_SEGMENT_DICTIONARY_TESTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_SEGMENT_DICTIONARY_TESTS))
#define IS_USER_SEGMENT_DICTIONARY_TESTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_USER_SEGMENT_DICTIONARY_TESTS))
#define USER_SEGMENT_DICTIONARY_TESTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_SEGMENT_DICTIONARY_TESTS, UserSegmentDictionaryTestsClass))

typedef struct _UserSegmentDictionaryTests UserSegmentDictionaryTests;
typedef struct _UserSegmentDictionaryTestsClass UserSegmentDictionaryTestsClass;
typedef struct _UserSegmentDictionaryTestsPrivate UserSegmentDictionaryTestsPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_USER_SENTENCE_DICTIONARY_TESTS (user_sentence_dictionary_tests_get_type ())
#define USER_SENTENCE_DICTIONARY_TESTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_SENTENCE_DICTIONARY_TESTS, UserSentenceDictionaryTests))
#define USER_SENTENCE_DICTIONARY_TESTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_USER_SENTENCE_DICTIONARY_TESTS, UserSentenceDictionaryTestsClass))
#define IS_USER_SENTENCE_DICTIONARY_TESTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_SENTENCE_DICTIONARY_TESTS))
#define IS_USER_SENTENCE_DICTIONARY_TESTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_USER_SENTENCE_DICTIONARY_TESTS))
#define USER_SENTENCE_DICTIONARY_TESTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_SENTENCE_DICTIONARY_TESTS, UserSentenceDictionaryTestsClass))

typedef struct _UserSentenceDictionaryTests UserSentenceDictionaryTests;
typedef struct _UserSentenceDictionaryTestsClass UserSentenceDictionaryTestsClass;
typedef struct _UserSentenceDictionaryTestsPrivate UserSentenceDictionaryTestsPrivate;

#define TYPE_USER_DICTIONARY_WITH_CONTEXT_TESTS (user_dictionary_with_context_tests_get_type ())
#define USER_DICTIONARY_WITH_CONTEXT_TESTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_DICTIONARY_WITH_CONTEXT_TESTS, UserDictionaryWithContextTests))
#define USER_DICTIONARY_WITH_CONTEXT_TESTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_USER_DICTIONARY_WITH_CONTEXT_TESTS, UserDictionaryWithContextTestsClass))
#define IS_USER_DICTIONARY_WITH_CONTEXT_TESTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_DICTIONARY_WITH_CONTEXT_TESTS))
#define IS_USER_DICTIONARY_WITH_CONTEXT_TESTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_USER_DICTIONARY_WITH_CONTEXT_TESTS))
#define USER_DICTIONARY_WITH_CONTEXT_TESTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_DICTIONARY_WITH_CONTEXT_TESTS, UserDictionaryWithContextTestsClass))

typedef struct _UserDictionaryWithContextTests UserDictionaryWithContextTests;
typedef struct _UserDictionaryWithContextTestsClass UserDictionaryWithContextTestsClass;
typedef struct _UserDictionaryWithContextTestsPrivate UserDictionaryWithContextTestsPrivate;
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _UserSegmentDictionaryTests {
	KkcTestCase parent_instance;
	UserSegmentDictionaryTestsPrivate * priv;
};

struct _UserSegmentDictionaryTestsClass {
	KkcTestCaseClass parent_class;
};

struct _UserSentenceDictionaryTests {
	KkcTestCase parent_instance;
	UserSentenceDictionaryTestsPrivate * priv;
};

struct _UserSentenceDictionaryTestsClass {
	KkcTestCaseClass parent_class;
};

struct _UserDictionaryWithContextTests {
	KkcTestCase parent_instance;
	UserDictionaryWithContextTestsPrivate * priv;
};

struct _UserDictionaryWithContextTestsClass {
	KkcTestCaseClass parent_class;
};

struct _UserDictionaryWithContextTestsPrivate {
	KkcContext* context;
	KkcUserDictionary* user_dictionary;
};


static gpointer user_segment_dictionary_tests_parent_class = NULL;
static gpointer user_sentence_dictionary_tests_parent_class = NULL;
static gpointer user_dictionary_with_context_tests_parent_class = NULL;

GType user_segment_dictionary_tests_get_type (void) G_GNUC_CONST;
enum  {
	USER_SEGMENT_DICTIONARY_TESTS_DUMMY_PROPERTY
};
UserSegmentDictionaryTests* user_segment_dictionary_tests_new (void);
UserSegmentDictionaryTests* user_segment_dictionary_tests_construct (GType object_type);
static void user_segment_dictionary_tests_test_load (UserSegmentDictionaryTests* self);
static void _user_segment_dictionary_tests_test_load_kkc_test_case_test_method (gpointer self);
static void user_segment_dictionary_tests_test_write (UserSegmentDictionaryTests* self);
static void _user_segment_dictionary_tests_test_write_kkc_test_case_test_method (gpointer self);
static void user_segment_dictionary_tests_real_set_up (KkcTestCase* base);
GType user_sentence_dictionary_tests_get_type (void) G_GNUC_CONST;
enum  {
	USER_SENTENCE_DICTIONARY_TESTS_DUMMY_PROPERTY
};
UserSentenceDictionaryTests* user_sentence_dictionary_tests_new (void);
UserSentenceDictionaryTests* user_sentence_dictionary_tests_construct (GType object_type);
static void user_sentence_dictionary_tests_test_load (UserSentenceDictionaryTests* self);
static void _user_sentence_dictionary_tests_test_load_kkc_test_case_test_method (gpointer self);
static void user_sentence_dictionary_tests_test_write (UserSentenceDictionaryTests* self);
static void _user_sentence_dictionary_tests_test_write_kkc_test_case_test_method (gpointer self);
static void _vala_array_add1 (KkcSegment*** array, int* length, int* size, KkcSegment* value);
static void _vala_array_add2 (KkcSegment*** array, int* length, int* size, KkcSegment* value);
static void _vala_array_add3 (KkcSegment*** array, int* length, int* size, KkcSegment* value);
static void user_sentence_dictionary_tests_real_set_up (KkcTestCase* base);
GType user_dictionary_with_context_tests_get_type (void) G_GNUC_CONST;
#define USER_DICTIONARY_WITH_CONTEXT_TESTS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_USER_DICTIONARY_WITH_CONTEXT_TESTS, UserDictionaryWithContextTestsPrivate))
enum  {
	USER_DICTIONARY_WITH_CONTEXT_TESTS_DUMMY_PROPERTY
};
UserDictionaryWithContextTests* user_dictionary_with_context_tests_new (void);
UserDictionaryWithContextTests* user_dictionary_with_context_tests_construct (GType object_type);
static void user_dictionary_with_context_tests_test_conversion (UserDictionaryWithContextTests* self);
static void _user_dictionary_with_context_tests_test_conversion_kkc_test_case_test_method (gpointer self);
static void user_dictionary_with_context_tests_test_phrase_conversion (UserDictionaryWithContextTests* self);
static void _user_dictionary_with_context_tests_test_phrase_conversion_kkc_test_case_test_method (gpointer self);
static void user_dictionary_with_context_tests_test_register (UserDictionaryWithContextTests* self);
static void _user_dictionary_with_context_tests_test_register_kkc_test_case_test_method (gpointer self);
static void __lambda2_ (UserDictionaryWithContextTests* self);
static void ___lambda2__kkc_context_request_selection_text (KkcContext* _sender, gpointer self);
static void __lambda3_ (UserDictionaryWithContextTests* self);
static void ___lambda3__kkc_context_request_selection_text (KkcContext* _sender, gpointer self);
static void user_dictionary_with_context_tests_real_set_up (KkcTestCase* base);
static void user_dictionary_with_context_tests_real_tear_down (KkcTestCase* base);
static void user_dictionary_with_context_tests_finalize (GObject* obj);
gint _vala_main (gchar** args, int args_length1);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static void _user_segment_dictionary_tests_test_load_kkc_test_case_test_method (gpointer self) {
#line 5 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	user_segment_dictionary_tests_test_load (self);
#line 144 "user-dictionary.c"
}


static void _user_segment_dictionary_tests_test_write_kkc_test_case_test_method (gpointer self) {
#line 6 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	user_segment_dictionary_tests_test_write (self);
#line 151 "user-dictionary.c"
}


UserSegmentDictionaryTests* user_segment_dictionary_tests_construct (GType object_type) {
	UserSegmentDictionaryTests * self = NULL;
#line 3 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	self = (UserSegmentDictionaryTests*) kkc_test_case_construct (object_type, "UserSegmentDictionary");
#line 5 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_test_case_add_test ((KkcTestCase*) self, "load", _user_segment_dictionary_tests_test_load_kkc_test_case_test_method, self);
#line 6 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_test_case_add_test ((KkcTestCase*) self, "write", _user_segment_dictionary_tests_test_write_kkc_test_case_test_method, self);
#line 2 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	return self;
#line 165 "user-dictionary.c"
}


UserSegmentDictionaryTests* user_segment_dictionary_tests_new (void) {
#line 2 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	return user_segment_dictionary_tests_construct (TYPE_USER_SEGMENT_DICTIONARY_TESTS);
#line 172 "user-dictionary.c"
}


static void user_segment_dictionary_tests_test_load (UserSegmentDictionaryTests* self) {
	gchar* srcdir = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_;
	GError * _inner_error_ = NULL;
#line 9 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_return_if_fail (self != NULL);
#line 183 "user-dictionary.c"
	{
		KkcUserSegmentDictionary* _tmp0_;
		KkcUserSegmentDictionary* _tmp1_;
#line 11 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp0_ = kkc_user_segment_dictionary_new ("test-user-segment-dictionary", &_inner_error_);
#line 11 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp1_ = _tmp0_;
#line 11 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (_tmp1_);
#line 11 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 195 "user-dictionary.c"
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
#line 10 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 10 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 14 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 10 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 211 "user-dictionary.c"
	}
	__finally0:
#line 10 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 10 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 10 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 10 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 222 "user-dictionary.c"
	}
#line 17 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp2_ = g_getenv ("srcdir");
#line 17 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 17 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	srcdir = _tmp3_;
#line 18 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_vala_assert (srcdir != NULL, "srcdir != null");
#line 232 "user-dictionary.c"
	{
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_;
		KkcUserSegmentDictionary* _tmp6_;
		KkcUserSegmentDictionary* _tmp7_;
#line 21 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp4_ = g_build_filename (srcdir, "user-segment-dictionary-good", NULL);
#line 21 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp5_ = _tmp4_;
#line 21 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp6_ = kkc_user_segment_dictionary_new (_tmp5_, &_inner_error_);
#line 21 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp7_ = _tmp6_;
#line 21 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (_tmp7_);
#line 21 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_free0 (_tmp5_);
#line 21 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 252 "user-dictionary.c"
			goto __catch1_g_error;
		}
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError* e = NULL;
#line 20 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 20 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 24 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 20 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 268 "user-dictionary.c"
	}
	__finally1:
#line 20 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 20 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_free0 (srcdir);
#line 20 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 20 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 20 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 281 "user-dictionary.c"
	}
	{
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_;
		KkcUserSegmentDictionary* _tmp10_;
		KkcUserSegmentDictionary* _tmp11_;
#line 28 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp8_ = g_build_filename (srcdir, "user-segment-dictionary-bad1", NULL);
#line 28 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp9_ = _tmp8_;
#line 28 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp10_ = kkc_user_segment_dictionary_new (_tmp9_, &_inner_error_);
#line 28 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp11_ = _tmp10_;
#line 28 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (_tmp11_);
#line 28 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_free0 (_tmp9_);
#line 28 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 302 "user-dictionary.c"
			goto __catch2_g_error;
		}
#line 30 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 307 "user-dictionary.c"
	}
	goto __finally2;
	__catch2_g_error:
	{
		GError* e = NULL;
#line 27 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 27 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 27 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 319 "user-dictionary.c"
	}
	__finally2:
#line 27 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 27 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_free0 (srcdir);
#line 27 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 27 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 27 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 332 "user-dictionary.c"
	}
	{
		gchar* _tmp12_ = NULL;
		gchar* _tmp13_;
		KkcUserSegmentDictionary* _tmp14_;
		KkcUserSegmentDictionary* _tmp15_;
#line 35 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp12_ = g_build_filename (srcdir, "user-segment-dictionary-bad2", NULL);
#line 35 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp13_ = _tmp12_;
#line 35 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp14_ = kkc_user_segment_dictionary_new (_tmp13_, &_inner_error_);
#line 35 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp15_ = _tmp14_;
#line 35 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (_tmp15_);
#line 35 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_free0 (_tmp13_);
#line 35 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 353 "user-dictionary.c"
			goto __catch3_g_error;
		}
#line 37 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 358 "user-dictionary.c"
	}
	goto __finally3;
	__catch3_g_error:
	{
		GError* e = NULL;
#line 34 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 34 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 34 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 370 "user-dictionary.c"
	}
	__finally3:
#line 34 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 34 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_free0 (srcdir);
#line 34 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 34 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 34 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 383 "user-dictionary.c"
	}
#line 9 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_free0 (srcdir);
#line 387 "user-dictionary.c"
}


static void user_segment_dictionary_tests_test_write (UserSegmentDictionaryTests* self) {
	KkcSegmentDictionary* dictionary = NULL;
	KkcSegmentDictionary* _tmp2_;
	KkcCandidate* _tmp3_;
	KkcCandidate* _tmp4_;
	KkcSegmentDictionary* _tmp5_;
	KkcCandidate* _tmp6_;
	KkcCandidate* _tmp7_;
	KkcSegmentDictionary* _tmp8_;
	KkcCandidate* _tmp9_;
	KkcCandidate* _tmp10_;
	KkcSegmentDictionary* _tmp11_;
	KkcCandidate* _tmp12_;
	KkcCandidate* _tmp13_;
	KkcSegmentDictionary* _tmp14_;
	KkcCandidate* _tmp15_;
	KkcCandidate* _tmp16_;
	KkcCandidate* candidate = NULL;
	KkcCandidate* _tmp17_;
	KkcSegmentDictionary* _tmp18_;
	KkcSegmentDictionary* _tmp19_;
	KkcSegmentDictionary* _tmp20_;
	GError * _inner_error_ = NULL;
#line 42 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_return_if_fail (self != NULL);
#line 43 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	dictionary = NULL;
#line 418 "user-dictionary.c"
	{
		KkcUserSegmentDictionary* _tmp0_ = NULL;
		KkcUserSegmentDictionary* _tmp1_;
#line 45 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp1_ = kkc_user_segment_dictionary_new ("test-user-segment-dictionary", &_inner_error_);
#line 45 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp0_ = _tmp1_;
#line 45 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 428 "user-dictionary.c"
			goto __catch4_g_error;
		}
#line 45 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (dictionary);
#line 45 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		dictionary = (KkcSegmentDictionary*) _tmp0_;
#line 435 "user-dictionary.c"
	}
	goto __finally4;
	__catch4_g_error:
	{
		GError* e = NULL;
#line 44 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 44 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 48 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 44 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 449 "user-dictionary.c"
	}
	__finally4:
#line 44 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 44 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (dictionary);
#line 44 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 44 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 44 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 462 "user-dictionary.c"
	}
#line 51 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp2_ = dictionary;
#line 51 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp3_ = kkc_candidate_new ("あい", FALSE, "愛", NULL, NULL);
#line 51 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp4_ = _tmp3_;
#line 51 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_segment_dictionary_select_candidate (_tmp2_, _tmp4_);
#line 51 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_object_unref0 (_tmp4_);
#line 53 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp5_ = dictionary;
#line 53 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp6_ = kkc_candidate_new ("あお", FALSE, "青", NULL, NULL);
#line 53 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp7_ = _tmp6_;
#line 53 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_segment_dictionary_select_candidate (_tmp5_, _tmp7_);
#line 53 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_object_unref0 (_tmp7_);
#line 55 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp8_ = dictionary;
#line 55 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp9_ = kkc_candidate_new ("あ お", FALSE, "青", NULL, NULL);
#line 55 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp10_ = _tmp9_;
#line 55 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_segment_dictionary_select_candidate (_tmp8_, _tmp10_);
#line 55 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_object_unref0 (_tmp10_);
#line 57 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp11_ = dictionary;
#line 57 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp12_ = kkc_candidate_new ("あu", TRUE, "会u", NULL, NULL);
#line 57 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp13_ = _tmp12_;
#line 57 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_segment_dictionary_select_candidate (_tmp11_, _tmp13_);
#line 57 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_object_unref0 (_tmp13_);
#line 59 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp14_ = dictionary;
#line 59 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp15_ = kkc_candidate_new ("あe", TRUE, "会e", NULL, NULL);
#line 59 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp16_ = _tmp15_;
#line 59 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_segment_dictionary_select_candidate (_tmp14_, _tmp16_);
#line 59 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_object_unref0 (_tmp16_);
#line 62 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp17_ = kkc_candidate_new ("あw", TRUE, "会w", NULL, NULL);
#line 62 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	candidate = _tmp17_;
#line 63 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp18_ = dictionary;
#line 63 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_segment_dictionary_select_candidate (_tmp18_, candidate);
#line 64 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp19_ = dictionary;
#line 64 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_segment_dictionary_purge_candidate (_tmp19_, candidate);
#line 66 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp20_ = dictionary;
#line 66 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_dictionary_save ((KkcDictionary*) _tmp20_, &_inner_error_);
#line 66 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 66 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (candidate);
#line 66 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (dictionary);
#line 66 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 66 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 66 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 542 "user-dictionary.c"
	}
#line 42 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_object_unref0 (candidate);
#line 42 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_object_unref0 (dictionary);
#line 548 "user-dictionary.c"
}


static void user_segment_dictionary_tests_real_set_up (KkcTestCase* base) {
	UserSegmentDictionaryTests * self;
#line 69 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	self = (UserSegmentDictionaryTests*) base;
#line 70 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_remove ("test-user-segment-dictionary");
#line 558 "user-dictionary.c"
}


static void user_segment_dictionary_tests_class_init (UserSegmentDictionaryTestsClass * klass) {
#line 1 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	user_segment_dictionary_tests_parent_class = g_type_class_peek_parent (klass);
#line 1 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	KKC_TEST_CASE_CLASS (klass)->set_up = user_segment_dictionary_tests_real_set_up;
#line 567 "user-dictionary.c"
}


static void user_segment_dictionary_tests_instance_init (UserSegmentDictionaryTests * self) {
}


GType user_segment_dictionary_tests_get_type (void) {
	static volatile gsize user_segment_dictionary_tests_type_id__volatile = 0;
	if (g_once_init_enter (&user_segment_dictionary_tests_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (UserSegmentDictionaryTestsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) user_segment_dictionary_tests_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UserSegmentDictionaryTests), 0, (GInstanceInitFunc) user_segment_dictionary_tests_instance_init, NULL };
		GType user_segment_dictionary_tests_type_id;
		user_segment_dictionary_tests_type_id = g_type_register_static (KKC_TYPE_TEST_CASE, "UserSegmentDictionaryTests", &g_define_type_info, 0);
		g_once_init_leave (&user_segment_dictionary_tests_type_id__volatile, user_segment_dictionary_tests_type_id);
	}
	return user_segment_dictionary_tests_type_id__volatile;
}


static void _user_sentence_dictionary_tests_test_load_kkc_test_case_test_method (gpointer self) {
#line 78 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	user_sentence_dictionary_tests_test_load (self);
#line 590 "user-dictionary.c"
}


static void _user_sentence_dictionary_tests_test_write_kkc_test_case_test_method (gpointer self) {
#line 79 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	user_sentence_dictionary_tests_test_write (self);
#line 597 "user-dictionary.c"
}


UserSentenceDictionaryTests* user_sentence_dictionary_tests_construct (GType object_type) {
	UserSentenceDictionaryTests * self = NULL;
#line 76 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	self = (UserSentenceDictionaryTests*) kkc_test_case_construct (object_type, "UserSentenceDictionary");
#line 78 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_test_case_add_test ((KkcTestCase*) self, "load", _user_sentence_dictionary_tests_test_load_kkc_test_case_test_method, self);
#line 79 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_test_case_add_test ((KkcTestCase*) self, "write", _user_sentence_dictionary_tests_test_write_kkc_test_case_test_method, self);
#line 75 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	return self;
#line 611 "user-dictionary.c"
}


UserSentenceDictionaryTests* user_sentence_dictionary_tests_new (void) {
#line 75 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	return user_sentence_dictionary_tests_construct (TYPE_USER_SENTENCE_DICTIONARY_TESTS);
#line 618 "user-dictionary.c"
}


static void user_sentence_dictionary_tests_test_load (UserSentenceDictionaryTests* self) {
	gchar* srcdir = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_;
	GError * _inner_error_ = NULL;
#line 82 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_return_if_fail (self != NULL);
#line 629 "user-dictionary.c"
	{
		KkcUserSentenceDictionary* _tmp0_;
		KkcUserSentenceDictionary* _tmp1_;
#line 84 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp0_ = kkc_user_sentence_dictionary_new ("user-sentence-dictionary", &_inner_error_);
#line 84 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp1_ = _tmp0_;
#line 84 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (_tmp1_);
#line 84 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 641 "user-dictionary.c"
			goto __catch5_g_error;
		}
	}
	goto __finally5;
	__catch5_g_error:
	{
		GError* e = NULL;
#line 83 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 83 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 87 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 83 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 657 "user-dictionary.c"
	}
	__finally5:
#line 83 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 83 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 83 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 83 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 668 "user-dictionary.c"
	}
#line 90 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp2_ = g_getenv ("srcdir");
#line 90 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 90 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	srcdir = _tmp3_;
#line 91 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_vala_assert (srcdir != NULL, "srcdir != null");
#line 678 "user-dictionary.c"
	{
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_;
		KkcUserSentenceDictionary* _tmp6_;
		KkcUserSentenceDictionary* _tmp7_;
#line 94 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp4_ = g_build_filename (srcdir, "user-sentence-dictionary-good", NULL);
#line 94 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp5_ = _tmp4_;
#line 94 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp6_ = kkc_user_sentence_dictionary_new (_tmp5_, &_inner_error_);
#line 94 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp7_ = _tmp6_;
#line 94 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (_tmp7_);
#line 94 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_free0 (_tmp5_);
#line 94 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 698 "user-dictionary.c"
			goto __catch6_g_error;
		}
	}
	goto __finally6;
	__catch6_g_error:
	{
		GError* e = NULL;
#line 93 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 93 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 97 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 93 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 714 "user-dictionary.c"
	}
	__finally6:
#line 93 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 93 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_free0 (srcdir);
#line 93 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 93 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 93 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 727 "user-dictionary.c"
	}
	{
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_;
		KkcUserSentenceDictionary* _tmp10_;
		KkcUserSentenceDictionary* _tmp11_;
#line 101 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp8_ = g_build_filename (srcdir, "user-sentence-dictionary-bad1", NULL);
#line 101 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp9_ = _tmp8_;
#line 101 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp10_ = kkc_user_sentence_dictionary_new (_tmp9_, &_inner_error_);
#line 101 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp11_ = _tmp10_;
#line 101 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (_tmp11_);
#line 101 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_free0 (_tmp9_);
#line 101 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 748 "user-dictionary.c"
			goto __catch7_g_error;
		}
#line 103 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 753 "user-dictionary.c"
	}
	goto __finally7;
	__catch7_g_error:
	{
		GError* e = NULL;
#line 100 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 100 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 100 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 765 "user-dictionary.c"
	}
	__finally7:
#line 100 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 100 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_free0 (srcdir);
#line 100 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 100 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 100 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 778 "user-dictionary.c"
	}
	{
		gchar* _tmp12_ = NULL;
		gchar* _tmp13_;
		KkcUserSentenceDictionary* _tmp14_;
		KkcUserSentenceDictionary* _tmp15_;
#line 108 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp12_ = g_build_filename (srcdir, "user-sentence-dictionary-bad2", NULL);
#line 108 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp13_ = _tmp12_;
#line 108 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp14_ = kkc_user_sentence_dictionary_new (_tmp13_, &_inner_error_);
#line 108 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp15_ = _tmp14_;
#line 108 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (_tmp15_);
#line 108 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_free0 (_tmp13_);
#line 108 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 799 "user-dictionary.c"
			goto __catch8_g_error;
		}
#line 110 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 804 "user-dictionary.c"
	}
	goto __finally8;
	__catch8_g_error:
	{
		GError* e = NULL;
#line 107 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 107 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 107 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 816 "user-dictionary.c"
	}
	__finally8:
#line 107 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 107 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_free0 (srcdir);
#line 107 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 107 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 107 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 829 "user-dictionary.c"
	}
#line 82 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_free0 (srcdir);
#line 833 "user-dictionary.c"
}


static void _vala_array_add1 (KkcSegment*** array, int* length, int* size, KkcSegment* value) {
#line 126 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if ((*length) == (*size)) {
#line 126 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 126 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		*array = g_renew (KkcSegment*, *array, (*size) + 1);
#line 844 "user-dictionary.c"
	}
#line 126 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	(*array)[(*length)++] = value;
#line 126 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	(*array)[*length] = NULL;
#line 850 "user-dictionary.c"
}


static void _vala_array_add2 (KkcSegment*** array, int* length, int* size, KkcSegment* value) {
#line 127 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if ((*length) == (*size)) {
#line 127 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 127 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		*array = g_renew (KkcSegment*, *array, (*size) + 1);
#line 861 "user-dictionary.c"
	}
#line 127 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	(*array)[(*length)++] = value;
#line 127 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	(*array)[*length] = NULL;
#line 867 "user-dictionary.c"
}


static void _vala_array_add3 (KkcSegment*** array, int* length, int* size, KkcSegment* value) {
#line 128 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if ((*length) == (*size)) {
#line 128 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 128 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		*array = g_renew (KkcSegment*, *array, (*size) + 1);
#line 878 "user-dictionary.c"
	}
#line 128 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	(*array)[(*length)++] = value;
#line 128 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	(*array)[*length] = NULL;
#line 884 "user-dictionary.c"
}


static void user_sentence_dictionary_tests_test_write (UserSentenceDictionaryTests* self) {
	KkcSentenceDictionary* dictionary = NULL;
	KkcSegment** segments = NULL;
	KkcSegment** _tmp2_ = NULL;
	gint segments_length1;
	gint _segments_size_;
	KkcSegment** _tmp3_;
	gint _tmp3__length1;
	KkcSegment* _tmp4_;
	KkcSegment** _tmp5_;
	gint _tmp5__length1;
	KkcSegment* _tmp6_;
	KkcSegment** _tmp7_;
	gint _tmp7__length1;
	KkcSegment* _tmp8_;
	KkcSentenceDictionary* _tmp9_;
	KkcSegment** _tmp10_;
	gint _tmp10__length1;
	KkcSentenceDictionary* _tmp11_;
	GError * _inner_error_ = NULL;
#line 115 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_return_if_fail (self != NULL);
#line 116 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	dictionary = NULL;
#line 912 "user-dictionary.c"
	{
		KkcUserSentenceDictionary* _tmp0_ = NULL;
		KkcUserSentenceDictionary* _tmp1_;
#line 118 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp1_ = kkc_user_sentence_dictionary_new ("test-user-sentence-dictionary", &_inner_error_);
#line 118 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp0_ = _tmp1_;
#line 118 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 922 "user-dictionary.c"
			goto __catch9_g_error;
		}
#line 118 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (dictionary);
#line 118 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		dictionary = (KkcSentenceDictionary*) _tmp0_;
#line 929 "user-dictionary.c"
	}
	goto __finally9;
	__catch9_g_error:
	{
		GError* e = NULL;
#line 117 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 117 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 121 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 117 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 943 "user-dictionary.c"
	}
	__finally9:
#line 117 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 117 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (dictionary);
#line 117 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 117 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 117 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 956 "user-dictionary.c"
	}
#line 124 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp2_ = g_new0 (KkcSegment*, 0 + 1);
#line 124 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	segments = _tmp2_;
#line 124 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	segments_length1 = 0;
#line 124 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_segments_size_ = segments_length1;
#line 126 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp3_ = segments;
#line 126 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp3__length1 = segments_length1;
#line 126 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp4_ = kkc_segment_new ("left", "LEFT");
#line 126 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_vala_array_add1 (&segments, &segments_length1, &_segments_size_, _tmp4_);
#line 127 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp5_ = segments;
#line 127 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp5__length1 = segments_length1;
#line 127 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp6_ = kkc_segment_new ("right", "RIGHT");
#line 127 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_vala_array_add2 (&segments, &segments_length1, &_segments_size_, _tmp6_);
#line 128 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp7_ = segments;
#line 128 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp7__length1 = segments_length1;
#line 128 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp8_ = kkc_segment_new ("\n", "\\");
#line 128 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_vala_array_add3 (&segments, &segments_length1, &_segments_size_, _tmp8_);
#line 130 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp9_ = dictionary;
#line 130 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp10_ = segments;
#line 130 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp10__length1 = segments_length1;
#line 130 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_sentence_dictionary_select_segments (_tmp9_, _tmp10_, _tmp10__length1);
#line 131 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp11_ = dictionary;
#line 131 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_dictionary_save ((KkcDictionary*) _tmp11_, &_inner_error_);
#line 131 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 131 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		segments = (_vala_array_free (segments, segments_length1, (GDestroyNotify) g_object_unref), NULL);
#line 131 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (dictionary);
#line 131 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 131 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 131 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 1014 "user-dictionary.c"
	}
#line 115 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	segments = (_vala_array_free (segments, segments_length1, (GDestroyNotify) g_object_unref), NULL);
#line 115 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_object_unref0 (dictionary);
#line 1020 "user-dictionary.c"
}


static void user_sentence_dictionary_tests_real_set_up (KkcTestCase* base) {
	UserSentenceDictionaryTests * self;
#line 134 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	self = (UserSentenceDictionaryTests*) base;
#line 135 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_remove ("test-user-sentence-dictionary");
#line 1030 "user-dictionary.c"
}


static void user_sentence_dictionary_tests_class_init (UserSentenceDictionaryTestsClass * klass) {
#line 74 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	user_sentence_dictionary_tests_parent_class = g_type_class_peek_parent (klass);
#line 74 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	KKC_TEST_CASE_CLASS (klass)->set_up = user_sentence_dictionary_tests_real_set_up;
#line 1039 "user-dictionary.c"
}


static void user_sentence_dictionary_tests_instance_init (UserSentenceDictionaryTests * self) {
}


GType user_sentence_dictionary_tests_get_type (void) {
	static volatile gsize user_sentence_dictionary_tests_type_id__volatile = 0;
	if (g_once_init_enter (&user_sentence_dictionary_tests_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (UserSentenceDictionaryTestsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) user_sentence_dictionary_tests_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UserSentenceDictionaryTests), 0, (GInstanceInitFunc) user_sentence_dictionary_tests_instance_init, NULL };
		GType user_sentence_dictionary_tests_type_id;
		user_sentence_dictionary_tests_type_id = g_type_register_static (KKC_TYPE_TEST_CASE, "UserSentenceDictionaryTests", &g_define_type_info, 0);
		g_once_init_leave (&user_sentence_dictionary_tests_type_id__volatile, user_sentence_dictionary_tests_type_id);
	}
	return user_sentence_dictionary_tests_type_id__volatile;
}


static void _user_dictionary_with_context_tests_test_conversion_kkc_test_case_test_method (gpointer self) {
#line 153 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	user_dictionary_with_context_tests_test_conversion (self);
#line 1062 "user-dictionary.c"
}


static void _user_dictionary_with_context_tests_test_phrase_conversion_kkc_test_case_test_method (gpointer self) {
#line 154 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	user_dictionary_with_context_tests_test_phrase_conversion (self);
#line 1069 "user-dictionary.c"
}


static void _user_dictionary_with_context_tests_test_register_kkc_test_case_test_method (gpointer self) {
#line 155 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	user_dictionary_with_context_tests_test_register (self);
#line 1076 "user-dictionary.c"
}


UserDictionaryWithContextTests* user_dictionary_with_context_tests_construct (GType object_type) {
	UserDictionaryWithContextTests * self = NULL;
	GError * _inner_error_ = NULL;
#line 144 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	self = (UserDictionaryWithContextTests*) kkc_test_case_construct (object_type, "UserDictionaryWithContext");
#line 1085 "user-dictionary.c"
	{
		KkcLanguageModel* model = NULL;
		KkcLanguageModel* _tmp0_ = NULL;
		KkcContext* _tmp1_;
#line 147 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp0_ = kkc_language_model_load ("sorted3", &_inner_error_);
#line 147 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		model = _tmp0_;
#line 147 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 147 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			if (_inner_error_->domain == KKC_LANGUAGE_MODEL_ERROR) {
#line 1098 "user-dictionary.c"
				goto __catch10_kkc_language_model_error;
			}
			goto __finally10;
		}
#line 148 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp1_ = kkc_context_new (model);
#line 148 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (self->priv->context);
#line 148 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		self->priv->context = _tmp1_;
#line 146 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (model);
#line 1111 "user-dictionary.c"
	}
	goto __finally10;
	__catch10_kkc_language_model_error:
	{
		GError* e = NULL;
		FILE* _tmp2_;
		GError* _tmp3_;
		const gchar* _tmp4_;
#line 146 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 146 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 150 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp2_ = stderr;
#line 150 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp3_ = e;
#line 150 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp4_ = _tmp3_->message;
#line 150 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		fprintf (_tmp2_, "%s\n", _tmp4_);
#line 146 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 1134 "user-dictionary.c"
	}
	__finally10:
#line 146 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 146 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 146 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 146 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return NULL;
#line 1145 "user-dictionary.c"
	}
#line 153 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_test_case_add_test ((KkcTestCase*) self, "conversion", _user_dictionary_with_context_tests_test_conversion_kkc_test_case_test_method, self);
#line 154 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_test_case_add_test ((KkcTestCase*) self, "phrase-conversion", _user_dictionary_with_context_tests_test_phrase_conversion_kkc_test_case_test_method, self);
#line 155 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_test_case_add_test ((KkcTestCase*) self, "register", _user_dictionary_with_context_tests_test_register_kkc_test_case_test_method, self);
#line 143 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	return self;
#line 1155 "user-dictionary.c"
}


UserDictionaryWithContextTests* user_dictionary_with_context_tests_new (void) {
#line 143 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	return user_dictionary_with_context_tests_construct (TYPE_USER_DICTIONARY_WITH_CONTEXT_TESTS);
#line 1162 "user-dictionary.c"
}


static void user_dictionary_with_context_tests_test_conversion (UserDictionaryWithContextTests* self) {
	gchar* srcdir = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	KkcContext* _tmp2_;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_;
	KkcContext* _tmp5_;
	KkcDictionaryList* _tmp6_;
	KkcDictionaryList* _tmp7_;
	KkcUserDictionary* _tmp10_;
	GError * _inner_error_ = NULL;
#line 158 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_return_if_fail (self != NULL);
#line 159 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp0_ = g_getenv ("srcdir");
#line 159 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 159 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	srcdir = _tmp1_;
#line 160 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_vala_assert (srcdir != NULL, "srcdir != null");
#line 161 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp2_ = self->priv->context;
#line 161 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp3_ = g_build_filename (srcdir, "conversions-user-dictionary.json", NULL);
#line 161 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp4_ = _tmp3_;
#line 161 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_test_utils_do_conversions (_tmp2_, _tmp4_);
#line 161 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_free0 (_tmp4_);
#line 165 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp5_ = self->priv->context;
#line 165 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp6_ = kkc_context_get_dictionaries (_tmp5_);
#line 165 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp7_ = _tmp6_;
#line 165 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_dictionary_list_save (_tmp7_);
#line 1206 "user-dictionary.c"
	{
		KkcUserDictionary* _tmp8_;
		KkcUserDictionary* _tmp9_;
#line 168 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp8_ = kkc_user_dictionary_new ("test-user-dictionary", &_inner_error_);
#line 168 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp9_ = _tmp8_;
#line 168 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (_tmp9_);
#line 168 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 1218 "user-dictionary.c"
			goto __catch11_g_error;
		}
	}
	goto __finally11;
	__catch11_g_error:
	{
		GError* e = NULL;
#line 167 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 167 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 170 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 167 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 1234 "user-dictionary.c"
	}
	__finally11:
#line 167 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 167 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_free0 (srcdir);
#line 167 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 167 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 167 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 1247 "user-dictionary.c"
	}
#line 173 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp10_ = self->priv->user_dictionary;
#line 173 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_dictionary_reload ((KkcDictionary*) _tmp10_, &_inner_error_);
#line 173 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 173 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_free0 (srcdir);
#line 173 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 173 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 173 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 1263 "user-dictionary.c"
	}
#line 158 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_free0 (srcdir);
#line 1267 "user-dictionary.c"
}


static void user_dictionary_with_context_tests_test_phrase_conversion (UserDictionaryWithContextTests* self) {
	gchar* srcdir = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	KkcContext* _tmp2_;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_;
	KkcContext* _tmp5_;
	KkcDictionaryList* _tmp6_;
	KkcDictionaryList* _tmp7_;
#line 176 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_return_if_fail (self != NULL);
#line 177 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp0_ = g_getenv ("srcdir");
#line 177 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 177 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	srcdir = _tmp1_;
#line 178 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_vala_assert (srcdir != NULL, "srcdir != null");
#line 179 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp2_ = self->priv->context;
#line 179 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp3_ = g_build_filename (srcdir, "conversions-user-dictionary-phrase.json", NULL);
#line 179 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp4_ = _tmp3_;
#line 179 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_test_utils_do_conversions (_tmp2_, _tmp4_);
#line 179 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_free0 (_tmp4_);
#line 183 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp5_ = self->priv->context;
#line 183 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp6_ = kkc_context_get_dictionaries (_tmp5_);
#line 183 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp7_ = _tmp6_;
#line 183 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_dictionary_list_save (_tmp7_);
#line 176 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_free0 (srcdir);
#line 1311 "user-dictionary.c"
}


static void __lambda2_ (UserDictionaryWithContextTests* self) {
	KkcContext* _tmp0_;
#line 188 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp0_ = self->priv->context;
#line 188 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_context_set_selection_text (_tmp0_, "abc");
#line 1321 "user-dictionary.c"
}


static void ___lambda2__kkc_context_request_selection_text (KkcContext* _sender, gpointer self) {
#line 187 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	__lambda2_ (self);
#line 1328 "user-dictionary.c"
}


static void __lambda3_ (UserDictionaryWithContextTests* self) {
	KkcContext* _tmp0_;
#line 212 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp0_ = self->priv->context;
#line 212 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_context_set_selection_text (_tmp0_, NULL);
#line 1338 "user-dictionary.c"
}


static void ___lambda3__kkc_context_request_selection_text (KkcContext* _sender, gpointer self) {
#line 211 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	__lambda3_ (self);
#line 1345 "user-dictionary.c"
}


static void user_dictionary_with_context_tests_test_register (UserDictionaryWithContextTests* self) {
	gulong handler_id = 0UL;
	KkcContext* _tmp0_;
	gulong _tmp1_ = 0UL;
	KkcContext* _tmp3_;
	KkcContext* _tmp4_;
	KkcContext* _tmp6_;
	KkcSegmentList* _tmp7_;
	KkcSegmentList* _tmp8_;
	gint _tmp9_;
	gint _tmp10_;
	KkcContext* _tmp11_;
	KkcSegmentList* _tmp12_;
	KkcSegmentList* _tmp13_;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_;
	KkcContext* _tmp16_;
	KkcContext* _tmp17_;
	KkcContext* _tmp18_;
	KkcDictionaryList* _tmp19_;
	KkcDictionaryList* _tmp20_;
	KkcContext* _tmp21_;
	KkcContext* _tmp22_;
	KkcContext* _tmp24_;
	KkcContext* _tmp25_;
	KkcContext* _tmp29_;
	KkcContext* _tmp30_;
	KkcContext* _tmp32_;
	KkcContext* _tmp33_;
	KkcContext* _tmp35_;
	KkcSegmentList* _tmp36_;
	KkcSegmentList* _tmp37_;
	gint _tmp38_;
	gint _tmp39_;
	KkcContext* _tmp40_;
	KkcSegmentList* _tmp41_;
	KkcSegmentList* _tmp42_;
	gchar* _tmp43_ = NULL;
	gchar* _tmp44_;
	KkcContext* _tmp45_;
	KkcContext* _tmp46_;
	GError * _inner_error_ = NULL;
#line 186 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_return_if_fail (self != NULL);
#line 187 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp0_ = self->priv->context;
#line 187 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp1_ = g_signal_connect_object (_tmp0_, "request-selection-text", (GCallback) ___lambda2__kkc_context_request_selection_text, self, 0);
#line 187 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	handler_id = _tmp1_;
#line 1399 "user-dictionary.c"
	{
		KkcContext* _tmp2_;
#line 191 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp2_ = self->priv->context;
#line 191 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		kkc_context_process_key_events (_tmp2_, "A-r a i SPC RET", &_inner_error_);
#line 191 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 191 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			if (_inner_error_->domain == KKC_KEY_EVENT_FORMAT_ERROR) {
#line 1410 "user-dictionary.c"
				goto __catch12_kkc_key_event_format_error;
			}
#line 191 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 191 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			g_clear_error (&_inner_error_);
#line 191 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			return;
#line 1419 "user-dictionary.c"
		}
	}
	goto __finally12;
	__catch12_kkc_key_event_format_error:
	{
		GError* e = NULL;
#line 190 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 190 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 193 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 190 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 1434 "user-dictionary.c"
	}
	__finally12:
#line 190 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 190 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 190 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 190 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 1445 "user-dictionary.c"
	}
#line 195 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp3_ = self->priv->context;
#line 195 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_context_reset (_tmp3_);
#line 196 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp4_ = self->priv->context;
#line 196 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_context_clear_output (_tmp4_);
#line 1455 "user-dictionary.c"
	{
		KkcContext* _tmp5_;
#line 199 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp5_ = self->priv->context;
#line 199 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		kkc_context_process_key_events (_tmp5_, "a i SPC", &_inner_error_);
#line 199 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 199 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			if (_inner_error_->domain == KKC_KEY_EVENT_FORMAT_ERROR) {
#line 1466 "user-dictionary.c"
				goto __catch13_kkc_key_event_format_error;
			}
#line 199 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 199 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			g_clear_error (&_inner_error_);
#line 199 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			return;
#line 1475 "user-dictionary.c"
		}
	}
	goto __finally13;
	__catch13_kkc_key_event_format_error:
	{
		GError* e = NULL;
#line 198 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 198 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 201 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 198 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 1490 "user-dictionary.c"
	}
	__finally13:
#line 198 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 198 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 198 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 198 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 1501 "user-dictionary.c"
	}
#line 203 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp6_ = self->priv->context;
#line 203 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp7_ = kkc_context_get_segments (_tmp6_);
#line 203 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp8_ = _tmp7_;
#line 203 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp9_ = kkc_segment_list_get_size (_tmp8_);
#line 203 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp10_ = _tmp9_;
#line 203 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_vala_assert (_tmp10_ == 1, "context.segments.size == 1");
#line 204 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp11_ = self->priv->context;
#line 204 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp12_ = kkc_context_get_segments (_tmp11_);
#line 204 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp13_ = _tmp12_;
#line 204 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp14_ = kkc_segment_list_get_output (_tmp13_);
#line 204 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp15_ = _tmp14_;
#line 204 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_vala_assert (g_strcmp0 (_tmp15_, "abc") == 0, "context.segments.get_output () == \"abc\"");
#line 204 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_free0 (_tmp15_);
#line 205 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp16_ = self->priv->context;
#line 205 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_context_reset (_tmp16_);
#line 206 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp17_ = self->priv->context;
#line 206 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_context_clear_output (_tmp17_);
#line 208 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp18_ = self->priv->context;
#line 208 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp19_ = kkc_context_get_dictionaries (_tmp18_);
#line 208 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp20_ = _tmp19_;
#line 208 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_dictionary_list_save (_tmp20_);
#line 210 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp21_ = self->priv->context;
#line 210 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_signal_handler_disconnect ((GObject*) _tmp21_, handler_id);
#line 211 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp22_ = self->priv->context;
#line 211 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_signal_connect_object (_tmp22_, "request-selection-text", (GCallback) ___lambda3__kkc_context_request_selection_text, self, 0);
#line 1553 "user-dictionary.c"
	{
		KkcContext* _tmp23_;
#line 215 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp23_ = self->priv->context;
#line 215 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		kkc_context_process_key_events (_tmp23_, "A-r a i SPC", &_inner_error_);
#line 215 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 215 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			if (_inner_error_->domain == KKC_KEY_EVENT_FORMAT_ERROR) {
#line 1564 "user-dictionary.c"
				goto __catch14_kkc_key_event_format_error;
			}
#line 215 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 215 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			g_clear_error (&_inner_error_);
#line 215 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			return;
#line 1573 "user-dictionary.c"
		}
	}
	goto __finally14;
	__catch14_kkc_key_event_format_error:
	{
		GError* e = NULL;
#line 214 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 214 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 217 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 214 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 1588 "user-dictionary.c"
	}
	__finally14:
#line 214 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 214 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 214 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 214 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 1599 "user-dictionary.c"
	}
#line 219 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp24_ = self->priv->context;
#line 219 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_context_reset (_tmp24_);
#line 220 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp25_ = self->priv->context;
#line 220 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_context_clear_output (_tmp25_);
#line 1609 "user-dictionary.c"
	{
		KkcUserDictionary* _tmp26_;
		KkcUserDictionary* _tmp27_;
#line 223 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp26_ = kkc_user_dictionary_new ("test-user-dictionary", &_inner_error_);
#line 223 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp27_ = _tmp26_;
#line 223 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (_tmp27_);
#line 223 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 1621 "user-dictionary.c"
			goto __catch15_g_error;
		}
	}
	goto __finally15;
	__catch15_g_error:
	{
		GError* e = NULL;
#line 222 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 222 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 225 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 222 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 1637 "user-dictionary.c"
	}
	__finally15:
#line 222 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 222 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 222 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 222 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 1648 "user-dictionary.c"
	}
	{
		KkcContext* _tmp28_;
#line 229 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp28_ = self->priv->context;
#line 229 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		kkc_context_process_key_events (_tmp28_, "a TAB", &_inner_error_);
#line 229 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 229 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			if (_inner_error_->domain == KKC_KEY_EVENT_FORMAT_ERROR) {
#line 1660 "user-dictionary.c"
				goto __catch16_kkc_key_event_format_error;
			}
#line 229 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 229 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			g_clear_error (&_inner_error_);
#line 229 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			return;
#line 1669 "user-dictionary.c"
		}
	}
	goto __finally16;
	__catch16_kkc_key_event_format_error:
	{
		GError* e = NULL;
#line 228 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 228 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 231 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 228 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 1684 "user-dictionary.c"
	}
	__finally16:
#line 228 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 228 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 228 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 228 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 1695 "user-dictionary.c"
	}
#line 233 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp29_ = self->priv->context;
#line 233 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_context_reset (_tmp29_);
#line 234 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp30_ = self->priv->context;
#line 234 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_context_clear_output (_tmp30_);
#line 1705 "user-dictionary.c"
	{
		KkcContext* _tmp31_;
#line 237 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp31_ = self->priv->context;
#line 237 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		kkc_context_process_key_events (_tmp31_, "a i SPC C-BackSpace", &_inner_error_);
#line 237 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 237 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			if (_inner_error_->domain == KKC_KEY_EVENT_FORMAT_ERROR) {
#line 1716 "user-dictionary.c"
				goto __catch17_kkc_key_event_format_error;
			}
#line 237 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 237 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			g_clear_error (&_inner_error_);
#line 237 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			return;
#line 1725 "user-dictionary.c"
		}
	}
	goto __finally17;
	__catch17_kkc_key_event_format_error:
	{
		GError* e = NULL;
#line 236 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 236 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 239 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 236 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 1740 "user-dictionary.c"
	}
	__finally17:
#line 236 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 236 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 236 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 236 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 1751 "user-dictionary.c"
	}
#line 241 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp32_ = self->priv->context;
#line 241 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_context_reset (_tmp32_);
#line 242 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp33_ = self->priv->context;
#line 242 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_context_clear_output (_tmp33_);
#line 1761 "user-dictionary.c"
	{
		KkcContext* _tmp34_;
#line 245 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp34_ = self->priv->context;
#line 245 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		kkc_context_process_key_events (_tmp34_, "a i SPC", &_inner_error_);
#line 245 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 245 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			if (_inner_error_->domain == KKC_KEY_EVENT_FORMAT_ERROR) {
#line 1772 "user-dictionary.c"
				goto __catch18_kkc_key_event_format_error;
			}
#line 245 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 245 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			g_clear_error (&_inner_error_);
#line 245 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			return;
#line 1781 "user-dictionary.c"
		}
	}
	goto __finally18;
	__catch18_kkc_key_event_format_error:
	{
		GError* e = NULL;
#line 244 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 244 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 247 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 244 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 1796 "user-dictionary.c"
	}
	__finally18:
#line 244 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 244 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 244 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 244 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 1807 "user-dictionary.c"
	}
#line 249 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp35_ = self->priv->context;
#line 249 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp36_ = kkc_context_get_segments (_tmp35_);
#line 249 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp37_ = _tmp36_;
#line 249 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp38_ = kkc_segment_list_get_size (_tmp37_);
#line 249 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp39_ = _tmp38_;
#line 249 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_vala_assert (_tmp39_ == 1, "context.segments.size == 1");
#line 250 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp40_ = self->priv->context;
#line 250 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp41_ = kkc_context_get_segments (_tmp40_);
#line 250 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp42_ = _tmp41_;
#line 250 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp43_ = kkc_segment_list_get_output (_tmp42_);
#line 250 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp44_ = _tmp43_;
#line 250 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_vala_assert (g_strcmp0 (_tmp44_, "abc") != 0, "context.segments.get_output () != \"abc\"");
#line 250 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_free0 (_tmp44_);
#line 251 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp45_ = self->priv->context;
#line 251 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_context_reset (_tmp45_);
#line 252 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp46_ = self->priv->context;
#line 252 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_context_clear_output (_tmp46_);
#line 1843 "user-dictionary.c"
}


static void user_dictionary_with_context_tests_real_set_up (KkcTestCase* base) {
	UserDictionaryWithContextTests * self;
	gboolean _tmp0_ = FALSE;
	GError * _inner_error_ = NULL;
#line 255 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	self = (UserDictionaryWithContextTests*) base;
#line 256 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp0_ = g_file_test ("test-user-dictionary", G_FILE_TEST_EXISTS);
#line 256 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_tmp0_) {
#line 1857 "user-dictionary.c"
		{
#line 258 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			kkc_test_utils_remove_dir ("test-user-dictionary", &_inner_error_);
#line 258 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			if (_inner_error_ != NULL) {
#line 1863 "user-dictionary.c"
				goto __catch19_g_error;
			}
		}
		goto __finally19;
		__catch19_g_error:
		{
			GError* e = NULL;
#line 257 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			e = _inner_error_;
#line 257 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			_inner_error_ = NULL;
#line 260 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			g_assert_not_reached ();
#line 257 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			_g_error_free0 (e);
#line 1879 "user-dictionary.c"
		}
		__finally19:
#line 257 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 257 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 257 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			g_clear_error (&_inner_error_);
#line 257 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			return;
#line 1890 "user-dictionary.c"
		}
	}
	{
		KkcUserDictionary* _tmp1_ = NULL;
		KkcUserDictionary* _tmp2_;
		KkcContext* _tmp3_;
		KkcDictionaryList* _tmp4_;
		KkcDictionaryList* _tmp5_;
		KkcUserDictionary* _tmp6_;
#line 265 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp2_ = kkc_user_dictionary_new ("test-user-dictionary", &_inner_error_);
#line 265 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp1_ = _tmp2_;
#line 265 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 1906 "user-dictionary.c"
			goto __catch20_g_error;
		}
#line 265 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (self->priv->user_dictionary);
#line 265 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		self->priv->user_dictionary = _tmp1_;
#line 267 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp3_ = self->priv->context;
#line 267 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp4_ = kkc_context_get_dictionaries (_tmp3_);
#line 267 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp5_ = _tmp4_;
#line 267 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp6_ = self->priv->user_dictionary;
#line 267 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		kkc_dictionary_list_add (_tmp5_, (KkcDictionary*) _tmp6_);
#line 1923 "user-dictionary.c"
	}
	goto __finally20;
	__catch20_g_error:
	{
		GError* e = NULL;
#line 264 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 264 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 269 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_assert_not_reached ();
#line 264 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 1937 "user-dictionary.c"
	}
	__finally20:
#line 264 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 264 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 264 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 264 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 1948 "user-dictionary.c"
	}
	{
		gchar* srcdir = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
		KkcSystemSegmentDictionary* dictionary = NULL;
		gchar* _tmp9_ = NULL;
		gchar* _tmp10_;
		KkcSystemSegmentDictionary* _tmp11_;
		KkcSystemSegmentDictionary* _tmp12_;
		KkcContext* _tmp13_;
		KkcDictionaryList* _tmp14_;
		KkcDictionaryList* _tmp15_;
#line 273 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp7_ = g_getenv ("srcdir");
#line 273 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp8_ = g_strdup (_tmp7_);
#line 273 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		srcdir = _tmp8_;
#line 274 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_vala_assert (srcdir != NULL, "srcdir != null");
#line 275 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp9_ = g_build_filename (srcdir, "system-segment-dictionary", NULL);
#line 275 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp10_ = _tmp9_;
#line 275 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp11_ = kkc_system_segment_dictionary_new (_tmp10_, "EUC-JP", &_inner_error_);
#line 275 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp12_ = _tmp11_;
#line 275 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_free0 (_tmp10_);
#line 275 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		dictionary = _tmp12_;
#line 275 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		if (_inner_error_ != NULL) {
#line 275 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
			_g_free0 (srcdir);
#line 1986 "user-dictionary.c"
			goto __catch21_g_error;
		}
#line 277 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp13_ = self->priv->context;
#line 277 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp14_ = kkc_context_get_dictionaries (_tmp13_);
#line 277 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp15_ = _tmp14_;
#line 277 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		kkc_dictionary_list_add (_tmp15_, (KkcDictionary*) dictionary);
#line 272 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_object_unref0 (dictionary);
#line 272 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_free0 (srcdir);
#line 2001 "user-dictionary.c"
	}
	goto __finally21;
	__catch21_g_error:
	{
		GError* e = NULL;
		FILE* _tmp16_;
		GError* _tmp17_;
		const gchar* _tmp18_;
#line 272 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		e = _inner_error_;
#line 272 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_inner_error_ = NULL;
#line 279 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp16_ = stderr;
#line 279 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp17_ = e;
#line 279 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_tmp18_ = _tmp17_->message;
#line 279 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		fprintf (_tmp16_, "%s\n", _tmp18_);
#line 272 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		_g_error_free0 (e);
#line 2024 "user-dictionary.c"
	}
	__finally21:
#line 272 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	if (_inner_error_ != NULL) {
#line 272 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 272 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		g_clear_error (&_inner_error_);
#line 272 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
		return;
#line 2035 "user-dictionary.c"
	}
}


static void user_dictionary_with_context_tests_real_tear_down (KkcTestCase* base) {
	UserDictionaryWithContextTests * self;
	KkcContext* _tmp0_;
	KkcDictionaryList* _tmp1_;
	KkcDictionaryList* _tmp2_;
#line 283 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	self = (UserDictionaryWithContextTests*) base;
#line 284 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp0_ = self->priv->context;
#line 284 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp1_ = kkc_context_get_dictionaries (_tmp0_);
#line 284 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp2_ = _tmp1_;
#line 284 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_dictionary_list_clear (_tmp2_);
#line 2055 "user-dictionary.c"
}


static void user_dictionary_with_context_tests_class_init (UserDictionaryWithContextTestsClass * klass) {
#line 139 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	user_dictionary_with_context_tests_parent_class = g_type_class_peek_parent (klass);
#line 139 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_type_class_add_private (klass, sizeof (UserDictionaryWithContextTestsPrivate));
#line 139 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	KKC_TEST_CASE_CLASS (klass)->set_up = user_dictionary_with_context_tests_real_set_up;
#line 139 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	KKC_TEST_CASE_CLASS (klass)->tear_down = user_dictionary_with_context_tests_real_tear_down;
#line 139 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	G_OBJECT_CLASS (klass)->finalize = user_dictionary_with_context_tests_finalize;
#line 2070 "user-dictionary.c"
}


static void user_dictionary_with_context_tests_instance_init (UserDictionaryWithContextTests * self) {
#line 139 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	self->priv = USER_DICTIONARY_WITH_CONTEXT_TESTS_GET_PRIVATE (self);
#line 2077 "user-dictionary.c"
}


static void user_dictionary_with_context_tests_finalize (GObject* obj) {
	UserDictionaryWithContextTests * self;
#line 139 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_USER_DICTIONARY_WITH_CONTEXT_TESTS, UserDictionaryWithContextTests);
#line 140 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_object_unref0 (self->priv->context);
#line 141 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_object_unref0 (self->priv->user_dictionary);
#line 139 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	G_OBJECT_CLASS (user_dictionary_with_context_tests_parent_class)->finalize (obj);
#line 2091 "user-dictionary.c"
}


GType user_dictionary_with_context_tests_get_type (void) {
	static volatile gsize user_dictionary_with_context_tests_type_id__volatile = 0;
	if (g_once_init_enter (&user_dictionary_with_context_tests_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (UserDictionaryWithContextTestsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) user_dictionary_with_context_tests_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UserDictionaryWithContextTests), 0, (GInstanceInitFunc) user_dictionary_with_context_tests_instance_init, NULL };
		GType user_dictionary_with_context_tests_type_id;
		user_dictionary_with_context_tests_type_id = g_type_register_static (KKC_TYPE_TEST_CASE, "UserDictionaryWithContextTests", &g_define_type_info, 0);
		g_once_init_leave (&user_dictionary_with_context_tests_type_id__volatile, user_dictionary_with_context_tests_type_id);
	}
	return user_dictionary_with_context_tests_type_id__volatile;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	GTestSuite* root = NULL;
	GTestSuite* _tmp0_ = NULL;
	UserSegmentDictionaryTests* _tmp1_;
	UserSegmentDictionaryTests* _tmp2_;
	GTestSuite* _tmp3_ = NULL;
	UserSentenceDictionaryTests* _tmp4_;
	UserSentenceDictionaryTests* _tmp5_;
	GTestSuite* _tmp6_ = NULL;
	UserDictionaryWithContextTests* _tmp7_;
	UserDictionaryWithContextTests* _tmp8_;
	GTestSuite* _tmp9_ = NULL;
#line 289 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	setlocale (LC_ALL, "");
#line 291 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_test_init (&args_length1, &args, NULL);
#line 292 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	kkc_init ();
#line 294 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp0_ = g_test_get_root ();
#line 294 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	root = _tmp0_;
#line 295 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp1_ = user_segment_dictionary_tests_new ();
#line 295 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp2_ = _tmp1_;
#line 295 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp3_ = kkc_test_case_get_suite ((KkcTestCase*) _tmp2_);
#line 295 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_test_suite_add_suite (root, _tmp3_);
#line 295 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_object_unref0 (_tmp2_);
#line 296 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp4_ = user_sentence_dictionary_tests_new ();
#line 296 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp5_ = _tmp4_;
#line 296 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp6_ = kkc_test_case_get_suite ((KkcTestCase*) _tmp5_);
#line 296 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_test_suite_add_suite (root, _tmp6_);
#line 296 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_object_unref0 (_tmp5_);
#line 297 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp7_ = user_dictionary_with_context_tests_new ();
#line 297 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp8_ = _tmp7_;
#line 297 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_tmp9_ = kkc_test_case_get_suite ((KkcTestCase*) _tmp8_);
#line 297 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_test_suite_add_suite (root, _tmp9_);
#line 297 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	_g_object_unref0 (_tmp8_);
#line 299 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_test_run ();
#line 301 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	result = 0;
#line 301 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	return result;
#line 2166 "user-dictionary.c"
}


int main (int argc, char ** argv) {
#line 288 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	g_type_init ();
#line 288 "/home/ueno/devel/libkkc/tests/user-dictionary.vala"
	return _vala_main (argv, argc);
#line 2175 "user-dictionary.c"
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



